main: live.chanakancloud.chanasmp.ChanaSMP
name: ChanaSMP
version: 0.1.7-DEV
api-version: 1.15
depend: [ProtocolLib, Citizens]
commands:
  freeze:
    description: To Freeze Player
    usage: /freeze [player_name]
    permission: chanasmp.commands.freeze
  unfreeze:
    description: unfreeze player
    usage: /unfreeze [player_name]
    permission: chanasmp.commands.unfreeze
  botduel:
    description: To Duel with a bot
    usage: /botduel
  chanasmp:
    description: Main command for the plugin
    usage: /chanasmp
