main: live.chanakancloud.chanasmp.ChanaSMP
name: ChanaSMP
version: 1.4.7-DEV
api-version: 1.15
depend: [ProtocolLib, Citizens]
commands:
  freeze:
    description: To Freeze Player
    usage: /freeze [player_name]
  unfreeze:
    description: unfreeze player
    usage: /unfreeze [player_name]
  botduel:
    description: To Duel with a bot
    usage: /botduel
  chanasmp:
    description: Main command for the plugin
    usage: /chanasmp
  jumpscare:
    description: To jumpscare someone
    usage: /jumpscare [player_name]

  fly:
    description: To fly while not in creative mode
    usage: /fly