main: live.chanakancloud.chanasmp.ChanaSMP
name: ChanaSMP
version: 0.1.0-DEV
api-version: 1.15
depend: [ProtocolLib]
commands:
  freeze:
    description: To Freeze Player
    usage: /freeze [player_name]
    permission: chanasmp.commands.freeze
  unfreeze:
    description: unfreeze player
    usage: /unfreeze [player_name]
    permission: chanasmp.commands.unfreeze
